### ISSUE TITLE
🚨 Surface RPC errors better

### ISSUE THREAD

**Issue by hardyjosh** [rainlanguage/arb-bot#128]
We need to surface RPC errors better, "failed to get vault balance" isn't the same as "this RPC is bouncing all our requests"

**Comment by rouzwelt** [comment]
@hardyjosh specification on this issue is a bit broad and has a lot of room for subjective interpretations, so maybe we can narrow things down a bit.

but 2 things: 
1st is that all errors wit their full stack details/msg/code etc object fields are logged into otel, these small phrases that we see on alerts is just a short phrase to be able to be shown on alerts channel effectively to just give some idea about what happened with alerts in general, those alerts phrases because they should not be considered as detailed error etc but they are just a general statement about the error that happened, and the error details then should be viewed in detail in hyperdx panel.

2nd from what I understand of this issue statement, do you mean to have some sort of check for when things are down ? if so a possible solution we can easily implement is to set up new alert on hyperdx with a criteria of like x many errors happing on y span of time to be considered things are down

let me know your thoughts
cc @thedavidmeister

**Comment by hardyjosh** [comment]
@rouzwelt i'm looking for better interpreting of the errors.

In this case, we were getting an RPC error with the message "we can't execute this request"

It would better if the alert showed this, rather than the error downstream "failed to get vault balance".

I agree we should keep this tightly scoped, so to resolve this issue, please return the underlying error as the alert message, instead of "failed to get vault balance"
